# @Testingpayload
# Feature: Testing Paylaod Service

#   @Sanity @EDTPayload
#   Scenario Outline: <TestCaseId> [Sanity] <Scenario>
#     Given User Hit API endpoint is 'http://localhost:1234/contacts'
#      When User Modify BaseURL With following Resources:
#     Then User Hit validate Token API for EDT with HttpsMethod "<HttpsMethod>" and "<payloadpath>" and "<ContentType>"
#     Then User validate the Token API Response with Status code "<StatusCode>" and validate "<ResponseMessage>" and validate the "<schemapath>"

#     Examples:
#       | TestCaseId | Scenario                                             | ContentType      | StatusCode | ResponseMessage | HttpsMethod | payloadpath          | schemapath |
#       | TestCaseId | Validate with valid Token and Payload | application/json |        200 |                 | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate with valid json file         | application/json |        200 |                 | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate with valid schema             | application/json |        200 |                 | POST        | EDTPayload\\EDT.json |            |

#   @Regression @EDTPayload1
#   Scenario Outline: <TestCaseId> [Regression] <Scenario>
#     Given User Hit API endpoint is 'http://localhost:1234/contacts'
#     Then User Hit with Token in EDT and HttpsMethod "<HttpsMethod>" with the "<payloadpath>" with different values in "<AttributePath>" and changed values to "<NewValue>" and "<ContentType>"
#     Then User validate the Token API Response with Status code "<StatusCode>" and validate "<ResponseMessage>" and validate the "<schemapath>"

#     Examples:
#       | TestCaseId | Scenario                                                                   | AttributePath          | NewValue    | ContentType      | StatusCode | ResponseMessage    | HttpsMethod | payloadpath          | schemapath |
#       | TestCaseId | Validate payload with Invalid Token and Payload                            |                        |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid type                                         | type                   | Non-visitor | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null type                                            | type                   | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty type                                           | type                   |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with invalid refernce                                     | reference              | safcdasf    | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null  refernce                                       | reference              | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty  refernce                                      | reference              |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid gender type                                  | gender                 |      324235 | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null gender type                                     | gender                 | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty gender type                                    | gender                 |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with invlaid title                                        | title                  |    24235325 | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null title                                           | title                  | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty title                                          | title                  |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing title field from the payload                  | title                  |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid first-name                                   | first-name             |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null first-name                                      | first-name             | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty first-name                                     | first-name             |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing first-name  field from the payload            | first-name             |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid last-name                                    | last-name              |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null last-name                                       | last-name              | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty last-name                                      | last-name              |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing last-name field from the payload              | last-name              |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid last-name                                    | last-name              |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null last-name                                       | last-name              | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty last-name                                      | last-name              |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing last-name field from the payload              | last-name              |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid company                                      | company                |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null company                                         | company                | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty company                                        | company                |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing company field from the payload                | company                |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid company                                      | company                |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null company                                         | company                | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty company                                        | company                |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing company field from the payload                | company                |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid job                                          | job-function           |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null job                                             | job-function           | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty job                                            | job-function           |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing job field from the payload                    | job-function           |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid phone number                                 | phone1                 |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null phone number                                    | phone1                 | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty phone number                                   | phone1                 |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing phone number field from the payload           | phone1                 |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid email id                                     | email                  |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null email id                                        | email                  | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty email id                                       | email                  |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing email id field from the payload               | email                  |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing addresses field from the payload              | addresses              |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty addresses                                      | addresses              |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null addresses                                       | addresses              | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid address type                                 | address-type           |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null address type                                    | address-type           | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty address type                                   | address-type           |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing address type field from the payload           | address-type           |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid name                                         | name                   |      3421## | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null name                                            | name                   | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty name                                           | name                   |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing name field from the payload                   | name                   |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null address                                         | address                | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty address                                        | address                |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing address field from the payload                | address                |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null house number                                    | house-number           | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty house number                                   | house-number           |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing house number field from the payload           | house-number           |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid postal code                                  | postal-code            | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null postal code                                     | postal-code            | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty postal code                                    | postal-code            |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing postal code field from the payload            | postal-code            |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid city                                         | city                   | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null city                                            | city                   | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty city                                           | city                   |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing city field from the payload                   | city                   |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid country                                      | country                | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null country                                         | country                | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty country                                        | country                |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing country field from the payload                | country                |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid state                                        | state                  | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null state                                           | state                  | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty state                                          | state                  |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing state field from the payload                  | state                  |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid registrant state                             | registrant-state       | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null registrant state                                | registrant-state       | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty registrant state                               | registrant-state       |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing registrant state field from the payload       | registrant-state       |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid attendance state                             | attendance-state       | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null attendance state                                | attendance-state       | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty attendance state                               | attendance-state       |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty attendance state                               | attendance-state       |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing attendance state field from the payload       | attendance-state       |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid  method                                      | method                 | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null  method                                         | method                 | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty  method                                        | method                 |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing method field from the payload                 | method                 |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid  register time                               | register-time          | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null  register time                                  | register-time          | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty  register time                                 | register-time          |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing register time field from the payload          | register-time          |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid event code                                   | event_code             | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null  event code                                     | event_code             | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty  event code                                    | event_code             |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing event code field from the payload             | event_code             |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid registration type code                       | registration-type-code | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null  registration type code                         | registration-type-code | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty  registration type code                        | registration-type-code |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing registration type code field from the payload | registration-type-code |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with Invalid tags                                         | tags                   | dsfs#$      | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with null tags                                            | tags                   | null        | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload with empty tags                                           | tags                   |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload by removing tags field from the payload                   | tags                   |             | application/json |        400 |                    | POST        | EDTPayload\\EDT.json |            |
#       | TestCaseId | Validate payload With Invalid Https Method                                 |                        |             | application/json |        405 | Method not allowed | GET         | EDTPayload\\EDT.json |            |

